steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout Repository with Submodules
        uses: actions/checkout@v6
        with:
          submodules: recursive      # สำคัญมาก
          fetch-depth: 0

      - name: Setup Android SDK, NDK and CMake
        uses: android-actions/setup-android@v3
        with:
          ndk-version: 29.0.14206865
          cmake-version: 3.31.5

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Grant Permissions for Gradle
        run: chmod +x gradlew

      - name: Build debug APK
        id: build
        run: ./gradlew assembleDebug --stacktrace
